language: python
python:
  - "2.7"

install:
  - pip install django

before_script:
  - echo "Antes de ejecutar un script"

script:
  - echo "Hola mundo"
  - pwd
  - ls -la
  - date
  - cd ladjfdfjjfdjdfjdfsj
  - echo "Finalizar"

notifications:
email: false